### ISSUE TITLE
No module named itkHelpers, itk 5.2.0

### ISSUE THREAD

**Issue by MOAMSA** [InsightSoftwareConsortium/ITK#2565] opened 2021-05-31 18:38 UTC
Hello,
Similar topics weren't helpful for me, so I have opened a new one.

I tried to use `MedialThicknessImageFilter3D` and got the below error:
`(<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'itkHelpers'")`

Image dimension: `512*512*3`.
Python 3.8
itk 5.2.0.post2
pip 21.1.2

I'd appreciate any suggestion.
Thanks

**Comment by dzenanz** [comment] 2021-05-31 19:33
This seems to be a duplicate of https://github.com/InsightSoftwareConsortium/ITKThickness3D/issues/39.

**Closed by dzenanz** 2021-05-31 19:33 UTC
Labels: type:Bug
