### ISSUE TITLE
Crash when use ImageFileReader read jpeg 

### ISSUE THREAD

**Issue by Hconk** [InsightSoftwareConsortium/ITK#2928] opened 2021-12-07 03:25 UTC
### Description
If compile with release version. When I use `ImageFileReader` read some broke jpeg image, it's crash in Update function. I expected throw an exception. 
But success in Debug.

### Steps to Reproduce
Build With Release. 
https://gist.github.com/Hconk/5b1bed75ebb3c62757277a1367d61edb

### Expected behavior
If image broke, expect throw an exception.

### Actual behavior
Crash at update. 

![image](https://user-images.githubusercontent.com/8470001/144960323-9cf583e8-8b78-4559-be58-218cb45e51e1.png)

![image](https://user-images.githubusercontent.com/8470001/144960311-6782e907-34bc-4cce-8fd1-28c1fdaf91f1.png)

### Reproducibility
Release Version. 

### Versions
c4960ee19c

### Environment
* CMake:  3.21.1
* OS: Centos 7.3 / Windows 10
* ITK Version:  5.2.1 / master branch
* compile: gcc10.2 / gcc 4.8 / vs2017

### Additional Information
Test data.
[Google Drive](https://drive.google.com/file/d/1rL4cmT8ZBqPEmyHny6MfByVg4wt_6MCQ/view?usp=sharing)

![211869_09365_55_55](https://user-images.githubusercontent.com/8470001/144959265-18556a05-b8c6-4ceb-b7e5-cae99ef917cd.jpg)

**Comment by dzenanz** [comment] 2021-12-07 14:52
I can't reproduce your error with a recent `master` 05ae9a5061555598bff524ff958fca66aa5b37db.
```c++
#include <itkJPEGImageIO.h>
#include <itkImageFileReader.h>

int main(int, char**) {
  constexpr unsigned int Dimension = 2;
  using PixelType = unsigned char;
  using ImageType = itk::Image<PixelType, Dimension>;
  itk::JPEGImageIO::Pointer io;
  io = itk::JPEGImageIO::New();
  itk::ImageFileReader<ImageType>::Pointer JPEGReader;
  JPEGReader = itk::ImageFileReader<ImageType>::New();
  JPEGReader->SetFileName("C:/a/211869_09365_55_55.jpg");
  JPEGReader->SetImageIO(io);
  try
  {
    JPEGReader->Update();
    std::cout << *JPEGReader->GetOutput();
  }
  catch (itk::ExceptionObject& err)
  {
    std::cerr << "ExceptionObject caught !" << std::endl;
    std::cerr << err << std::endl;
  }

  std::cout << "ITK Read Jpeg Demo.\n";
  return 0;
}
```
produces
```text
Image (0000028596779BF0)
  RTTI typeinfo:   class itk::Image<unsigned char,2>
  Reference Count: 1
  Modified Time: 76
  Debug: Off
  Object Name:
  Observers:
    none
  Source: (00000285967745B0)
  Source output name: Primary
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 68
  UpdateMTime: 77
  RealTimeStamp: 0 seconds
  LargestPossibleRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [1200, 1400]
  BufferedRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [1200, 1400]
  RequestedRegion:
    Dimension: 2
    Index: [0, 0]
    Size: [1200, 1400]
  Spacing: [1, 1]
  Origin: [0, 0]
  Direction:
1 0
0 1

  IndexToPointMatrix:
1 0
0 1

  PointToIndexMatrix:
1 0
0 1

  Inverse Direction:
1 0
0 1

  PixelContainer:
    ImportImageContainer (0000028596779E20)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned __int64,unsigned char>
      Reference Count: 1
      Modified Time: 74
      Debug: Off
      Object Name:
      Observers:
        none
      Pointer: 00000285969BF070
      Container manages memory: true
      Size: 1680000
      Capacity: 1680000
ITK Read Jpeg Demo.

C:\Misc\Tester\Debug\tester.exe (process 29296) exited with code 0.
```

**Comment by Hconk** [comment] 2021-12-08 01:22
Did you test with the release version? I only reproduce in release.

**Comment by dzenanz** [comment] 2021-12-08 15:20
I tried both `Debug` and `RelWithDebInfo` builds, and they both work.

**Comment by issakomi** [comment] 2021-12-08 17:50
On Debian 10 the files crashes everything related to ITK's JPEG IO: my app, Slicer (tested nightly build), that test program. In _Release_ and _RelWithDebInfo_ builds, _Debug_ builds survive. Eye of Mate and Gimp doesn't crash. The file is broken. I don't hope that _RelWithDebInfo_ can be useful, points c in my app and test app to different code, not sure. Probably _Debug_ build and Valgrind might help. I shall try later to look closer, that crash in my paid program is worrying.

**Comment by issakomi** [comment] 2021-12-09 03:37
Probably i have done a temporary fixed... 
The error happens in _jpeg_destroy_decompress(&cinfo);_ I have re-written several times the [Read](https://github.com/InsightSoftwareConsortium/ITK/blob/217c0d408487d454cf9b0f945ab5575c2322ee7a/Modules/IO/JPEG/src/itkJPEGImageIO.cxx#L172) function to find it out and tested version 4.12 with system JPEG (also crashed, BTW). So finally i looked inside Gimp code (Gimp doesn't fail on the file).
The minimal solution is to add `if (setjmp (jerr.setjmp_buffer))` block at the beginning of the _while_ loop

```
  // read the bulk data
  unsigned int remainingRows;
  while (cinfo.output_scanline < cinfo.output_height)
  {
    if (setjmp (jerr.setjmp_buffer))                // <------------------------
    {                                                             // <------------------------
      std::cout << "goto quit:" << std::endl;  // <------------------------
      goto quit;                                             // <------------------------
    }                                                            // <------------------------
    remainingRows = cinfo.output_height - cinfo.output_scanline;
    jpeg_read_scanlines(&cinfo, &row_pointers[cinfo.output_scanline], remainingRows);
  }
```

and **quit:** before _jpeg_destroy_decompress_ at the end of Read function, to skip _jpeg_finish_decompress_ call in case of an error.

```
quit:             // <-------------------
  // destroy the decompression object
  jpeg_destroy_decompress(&cinfo);

  delete[] row_pointers;
}
```

@Hconk May be you could validate?

P.S. Please don't write me that "goto" is bad. It is not the final solution, it is minimal working for now. There several possible another non-critical issues in the function, specially _remainingRows_ in _jpeg_read_scanlines_, at a first look sseem that this may be a mistake and some rows are processed many times. Also  _row_pointer_ new/delete can be easily avoided, IMHO.

**Comment by Hconk** [comment] 2021-12-09 06:23
@issakomi Thanks, I validate your patch code, It's work for me, This problem has bothered me for a long time.

**Comment by Hconk** [comment] 2021-12-09 06:44
> I tried both `Debug` and `RelWithDebInfo` builds, and they both work.

Thanks for you tried, I use Github Action build this demo to reproduce this case. 

Demo Project: https://github.com/Hconk/ReadJpegDemo
Test  with Debug result: https://github.com/Hconk/ReadJpegDemo/runs/4466987270?check_suite_focus=true
Test  with Release result: https://github.com/Hconk/ReadJpegDemo/runs/4466987349?check_suite_focus=true

I temporarily use @issakomi solution to fix the problem.If the final solution is updated, I would be happy to verify.

**Comment by issakomi** [comment] 2021-12-09 09:45
@Hconk  Thank you for testing.

If ITK wish the change, s.
https://github.com/InsightSoftwareConsortium/ITK/compare/master...issakomi:jpegio

It is exactly the same, but probably closer to ITK style.

For reference s. [similar GIMP approach](https://gist.github.com/issakomi/eafe45ab32913609856aae680b564cb4#file-jpeg-load-c-L367)


P.S.
> There are several possible another non-critical issues in the function, specially remainingRows in jpeg_read_scanlines

It is OK, probably no issue here, tested return values of _jpeg_read_scanlines_, usuall 1-2 lines are de-facto read, but passing max lines is valid.

**Comment by Hconk** [comment] 2021-12-09 09:54
@issakomi Great, I need process large number of images, some warnning maybe help me find broken image. Thanks for your work.

**Comment by issakomi** [comment] 2021-12-09 11:31
Maybe i am going to understand where the undefined behavior is from (that strange issues with Debug/Release, different Valgrind error, etc). I suspect that wrapping of _setjmp_ may be the issue, it is extremely sensitive macro, i shall check it and probably make a PR, maybe.

**Comment by issakomi** [comment] 2021-12-09 12:13
Yes. Wrapping of setjump [here](https://github.com/InsightSoftwareConsortium/ITK/blob/217c0d408487d454cf9b0f945ab5575c2322ee7a/Modules/IO/JPEG/src/itkJPEGImageIO.cxx#L58) is **bug**.

I have replaced _wrapSetjmp(itk_jpeg_error_mgr & jerr)_ everywhere with `(setjmp(jerr.setjmp_buffer))` **without** that temporary fix above and results of the test program is:

```
r@deb:~/Desktop/test_jpeg/build$ ./readjpeg 
ExceptionObject caught !

itk::ExceptionObject (0x555e03ae2d40)
Location: "unknown" 
File: /home/r/itkf/ITK/Modules/IO/JPEG/src/itkJPEGImageIO.cxx
Line: 202
Description: ITK ERROR: JPEGImageIO(0x555e03adee50): libjpeg could not read file: bug.jpg


ITK Read Jpeg Demo.
```

I shall look closer.

**Comment by issakomi** [comment] 2021-12-09 14:41
https://github.com/InsightSoftwareConsortium/ITK/compare/master...issakomi:jpeg

Only [itkJPEGImageIO](https://github.com/issakomi/ITK/blob/jpeg/Modules/IO/JPEG/src/itkJPEGImageIO.cxx) changed.

Works as expected, WIP. 

There are also some style changes, sorry _auto_ and _reinterpret_cast_ hurt my eyes in `extern C` function, the file is primary for my own usage.

**Comment by issakomi** [comment] 2021-12-09 15:14
Only C-style instead _auto_ and _reinterpret_cast_ in [extern "C" function](https://github.com/issakomi/ITK/blob/de360833e01134e0355632d5d3f4a1b12c3345aa/Modules/IO/JPEG/src/itkJPEGImageIO.cxx#L35) and this possible leak [here](https://github.com/issakomi/ITK/blob/de360833e01134e0355632d5d3f4a1b12c3345aa/Modules/IO/JPEG/src/itkJPEGImageIO.cxx#L525) may be considered as optional, all the rest is required, IMHO.

**Comment by issakomi** [comment] 2021-12-10 04:20
> Could a PR please be made with the "minimal" fix?
> 
 @blowekamp  it was my 1st idea to use the solution from this [post](https://github.com/InsightSoftwareConsortium/ITK/issues/2928#issuecomment-989479032) and stay with 6-lines patch. But then I had tried to turn `(setjmp(jerr.setjmp_buffer))` into `wrapSetjmp(err)` to be consistent with the style of the class and added a warning, strange issues appeared. I replaced other [wraps](https://github.com/InsightSoftwareConsortium/ITK/blob/217c0d408487d454cf9b0f945ab5575c2322ee7a/Modules/IO/JPEG/src/itkJPEGImageIO.cxx#L58) with direct  _setjumps_ and this changed the behavior again, s. [post](https://github.com/InsightSoftwareConsortium/ITK/issues/2928#issuecomment-989796740).

**Comment by issakomi** [comment] 2021-12-10 05:21
BTW, i realized that JPEG errors are supressed
`METHODDEF(void) itk_jpeg_output_message(j_common_ptr) {}`

With error output enabled the messages for the file are:
```
Corrupt JPEG data: premature end of data segment
Unsupported marker type 0x02
```

**Comment by Hconk** [comment] 2021-12-11 14:37
@dzenanz @issakomi 
I found some specially constructed png image also cause crash. When I use `PNGImageIO` read it ,will got some libpng error infomation `libpng error: PNG unsigned integer out of range` then crash. I think it's need throw exception. 
Although it is not generated in a real scene, may also need to be fixed. (Maybe need open a new issue.)

Example test data: https://drive.google.com/file/d/1wRMTQlz31lwccha9hdPb-uTwNXD77nZv/view?usp=sharing
image sha256: f82d996c02975eecbdf0823bad5047124d3d146a0fb8804e377c35838ed264b8
Good image: 
```
λ Desktop itk_demo → cat ./good.png | xxd -u
00000000: 8950 4E47 0D0A 1A0A 0000 000D 4948 4452  .PNG........IHDR
00000010: 0000 0001 0000 0001 0100 0000 0037 6EF9  .............7n.
00000020: 2400 0000 1049 4441 5478 9C62 6001 0000  $....IDATx.b`...
00000030: 00FF FF03 0000 0600 0557 BFAB D400 0000  .........W......
00000040: 0049 454E 44AE 4260 82                   .IEND.B`.
```

Broken png image hex:
```
λ Desktop itk_demo → cat ./corrupted.png | xxd -u
00000000: 8950 4E47 0D0A 1A0A 0000 000D 4948 4452  .PNG........IHDR
00000010: 0000 0001 0000 0001 0100 0000 0037 6EF9  .............7n.
00000020: 24FF 0000 1049 4441 5478 9C62 6001 0000  $....IDATx.b`...
00000030: 00FF FF03 0000 0600 0557 BFAB D400 0000  .........W......
00000040: 0049 454E 44AE 4260 82                   .IEND.B`.
```
The difference between the two pictures is at the 0x21st byte.

**Comment by issakomi** [comment] 2021-12-11 21:36
Thank you!
Yes, the same, on Debian 10: my app and Slicer crash, Eye of Mate and Gimp don't:

![Screenshot at 2021-12-11 22-30-55](https://user-images.githubusercontent.com/1494580/145692340-1f7f4b18-ced8-439b-a946-dee78f238755.png)

![Screenshot at 2021-12-11 22-31-14](https://user-images.githubusercontent.com/1494580/145692343-d982b3ae-b8d4-4522-86d8-49396b606529.png)

**Comment by issakomi** [comment] 2021-12-12 00:40
Fixed in **WIP** branch

https://github.com/InsightSoftwareConsortium/ITK/compare/master...issakomi:pngio

**Comment by thewtex** [comment] 2021-12-22 18:44
:clap: :pray: thanks @issakomi for the patches! Can this issue now be close?

**Comment by Hconk** [comment] 2021-12-23 01:16
> 👏 🙏 thanks @issakomi for the patches! Can this issue now be close?

 Yes, the problem is solved.

**Closed** 2021-12-23 02:10 UTC
Labels: type:Bug, area:IO
