### ISSUE TITLE
"vtk_module_config" removed from VTK

### ISSUE THREAD

**Issue by fbudin69500** [InsightSoftwareConsortium/ITK#424] opened 2019-01-17 19:35 UTC
### Description

`VtkGlue` doesn't compile with latest version of VTK (new module structure). I expect `LevelSetsv4Visualization` to have the same problem.

### Steps to Reproduce

1. Clone VTK github repository and compile it
2. Compile ITK with VtkGlue ON

### Expected behavior

CMake should configure the project correctly.

### Actual behavior

Currently, the following CMake error is printed:

`Unknown CMake command "vtk_module_config"`

### Reproducibility

All the time.

### Versions

VTK version > 8.2.0 will have this problem as the required CMake macro used by ITK to configure the remote modules that use VTK has been removed from VTK in commit 8d61ac62bfb3c532d1d3506d5f7fd495e49c4295.

### Environment

Ubuntu 18.04 but this should happen on any environment.

### Additional Information

This issue arises because the VTK module system has been fully reworked. A person that knows the new module system could probably fix the problem really fast. Information about the new VTK module system should be posted in this issue to help the person that is going to fix this problem.

**Comment by dzenanz** [comment] 2019-01-17 19:42
`LevelSetsv4Visualization` has been broken for a while, see Corista build [here](https://open.cdash.org/index.php?project=Insight#!#Expected_Nightly_Remote_Modules), but it has been manifesting itself as runtime error when visualizing something is attempted.

`LevelSetsv4Visualization`'s CMake code seems to be mostly duplicated from VTKGlue. It would be good if that duplication is gotten rid of, and simple dependency between them is introduced.

**Comment by fbudin69500** [comment] 2019-01-17 19:47
Related documentation:
http://vtk.1045678.n5.nabble.com/New-module-system-preview-td5748974.html

**Comment by seanm** [comment] 2019-01-17 22:54
@seanm CC'ing myself...

**Comment by schmidje** [comment] 2019-01-22 10:37
I can confirm this issue is also happening in Windows (visual studio 2017).

**Comment by seanm** [comment] 2019-01-23 16:44
VTK's new module system was merged exactly 2 weeks ago now (January 9), any chance ITK can be working with VTK again soon?

**Comment by seanm** [comment] 2019-02-05 20:00
So I guess nobody at Kitware uses VTK & ITK together? :(

**Comment by dzenanz** [comment] 2019-02-05 20:05
There are many combinations of versions and modules, so not all are routinely used/tested.

**Comment by seanm** [comment] 2019-02-05 20:13
If I'm not mistaken, it's not an obscure combination that's broken, but a vanilla VTK git master + ITK git master.  It's been broken since Kitware made the big build system changes in VTK the other week.

**Comment by thewtex** [comment] 2019-02-06 13:33
@schmidje well done on the update! Could it be [contributed to the repository](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md)?

**Comment by schmidje** [comment] 2019-02-06 14:32
@thewtex Well itk does build but I had to add additional mess on the file to be able to use ITKVtkGlue outside of itk, and honestly I am definitively not sure that the fixes will work. In this context, itk gurus of the cmake modules should instead investigate closely the issue....

I also found that the exported targets do NOT include the include paths of the targets... (whereas vtk does it properly in the new update) which somehow reduce the interest as you cannot just use a target_link_library(...someItkModule...) and have the include paths set automatically. But this is another story...!

**Comment by thewtex** [comment] 2019-02-06 16:15
@schmidje did you also add the compatibility macro to `ITKVtkGlue_EXPORT_CODE_INSTALL` and `ITKVtkGlue_EXPORT_CODE_BUILD`?

**Comment by schmidje** [comment] 2019-02-06 18:37
@thewtex Well it looks like I did:

I put in the ``ITKVtkGlue_EXPORT_CODE_INSTALL`` part: 

```cmake

set(ITKVtkGlue_EXPORT_CODE_INSTALL "
set(VTK_DIR \"${VTK_DIR}\")

find_package(VTK NO_MODULE REQUIRED)

# included part starts here
  if(NOT COMMAND vtk_module_config)
    macro(vtk_module_config ns)   
       foreach(arg \${ARGN})  
        if(\${arg} MATCHES \"^[Vv][Tt][Kk]\")
          string(REGEX REPLACE \"^[Vv][Tt][Kk]\" \"\" _arg \${arg})
        else()
          set(_arg \${arg})
        endif()
        set(\${ns}_LIBRARIES \${\${ns}_LIBRARIES} VTK::\${_arg})
       endforeach()
    endmacro()
  endif()
# included part ends here

if(NOT VTK_VERSION)

(...continues)
```
Then in the ``ITKVtkGlue_EXPORT_CODE_BUILD`` I did the same:

```cmake
set(ITKVtkGlue_EXPORT_CODE_BUILD "
if(NOT ITK_BINARY_DIR)
  set(VTK_DIR \"${VTK_DIR}\")
  
# included part starts here
  if(NOT COMMAND vtk_module_config)
    macro(vtk_module_config ns)   
       foreach(arg \${ARGN})  
        if(\${arg} MATCHES \"^[Vv][Tt][Kk]\")
          string(REGEX REPLACE \"^[Vv][Tt][Kk]\" \"\" _arg \${arg})
        else()
          set(_arg \${arg})
        endif()
        set(\${ns}_LIBRARIES \${\${ns}_LIBRARIES} VTK::\${_arg})
       endforeach()
    endmacro()
  endif()
# included part ends here

  find_package(VTK NO_MODULE REQUIRED)
(...continues)
```

**Comment by thewtex** [comment] 2019-02-06 18:51
@schmidje nice. Could you please create a pull request with the current WIP, so you get credit for your work?

CC: @mathstuf

**Comment by seanm** [comment] 2019-02-08 17:55
@lorensen Bill, maybe since you got all the VTKExamples working with the recent VTK changes, you would know how to get ITK working with VTK again?

**Comment by schmidje** [comment] 2019-02-10 20:35
@thewtex Well I could but first I would like to make sure it is working properly. I messed up some stuff with the update of itk, so I will try to make a test asap.

BR

**Comment by dzenanz** [comment] 2019-04-09 20:34
@schmidje any progress on turning this into a PR?

**Comment by schmidje** [comment] 2019-04-09 21:09
@dzenanz No, because until very recently I did not test the fix as my itk was not compiling anymore due to conflicts with a system Eigen lib. Now it seems to be ok and I can use VTK and ITK in a same app using the glue so I guess the fix is okay.

Now I don't have experience in submitting pull request to itk and the doc at https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md looks a little intimidating at first. Is this the correct way to go?

**Comment by dzenanz** [comment] 2019-04-09 21:12
Yes, [CONTRIBUTING](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md) has the instructions. `Setup`, `create a topic` and `share a topic` are the more important sections to get started.

**Comment by schmidje** [comment] 2019-04-13 19:52
Hi,

I tried to share my topic but I get this error at the `git review-push --force` stage:
```

$ git review-push --force
Pushing to origin
remote: Permission to InsightSoftwareConsortium/ITK.git denied to schmidje.
fatal: unable to access 'https://github.com/InsightSoftwareConsortium/ITK.git/': The requested URL returned error: 403
```

All previous steps listed in the document went smoothly. Am I missing something?

Thanks

**Comment by dzenanz** [comment] 2019-04-13 23:19
Origin should be your fork (`git@github.com:schmidje/ITK.git`). Upstream should be `https://github.com/InsightSoftwareConsortium/ITK.git`.

**Comment by schmidje** [comment] 2019-04-14 13:40
Thanks. I did not fork ITK in the first place but only made a local clone.

PR submitted to: [https://github.com/InsightSoftwareConsortium/ITK/pull/731](https://github.com/InsightSoftwareConsortium/ITK/pull/731)

BR,

**Closed** 2019-04-15 19:47 UTC
Labels: area:ThirdParty

**Comment by seanm** [comment] 2019-04-16 02:03
Could this go in ITK 4.x also?  Would be helpful when regression testing VTK/ITK combos...

**Comment by thewtex** [comment] 2019-04-23 22:08
@schmidje thanks for the contribution! :1st_place_medal: 

> Could this go in ITK 4.x also? Would be helpful when regression testing VTK/ITK combos...

@seanm yes, this has been [pushed to the `release-4.13` branch](https://github.com/InsightSoftwareConsortium/ITK/commit/c2cfd2b6d1afe9d8a2143b01e49ac6cb0ef97547).
