### ISSUE TITLE
Building with Python support

### ISSUE THREAD

**Issue by TheChymera** [InsightSoftwareConsortium/ITK#1229] opened 2019-09-04 17:42 UTC
As part of my build update adventure, I have come to what I hope is the last quest until the next release.

When building ITK with python support:

```
cmake -C /var/tmp/portage/sci-libs/itk-5.0.1/work/itk-5.0.1_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=ON -DGDCM_USE_SYSTEM_OPENJPEG=ON -DITK_FORBID_DOWNLOADS:BOOL=OFF -DITK_USE_SYSTEM_DCMTK=ON -DITK_USE_SYSTEM_DOUBLECONVERSION=ON -DITK_USE_SYSTEM_CASTXML=ON -DITK_USE_SYSTEM_HDF5=ON -DITK_USE_SYSTEM_JPEG=ON -DITK_USE_SYSTEM_PNG=ON -DITK_USE_SYSTEM_SWIG=ON -DITK_USE_SYSTEM_TIFF=ON -DITK_USE_SYSTEM_ZLIB=ON -DITK_USE_KWSTYLE=OFF -DITK_BUILD_DEFAULT_MODULES=ON -DITK_COMPUTER_MEMORY_SIZE=1 -DWRAP_ITK_JAVA=OFF -DWRAP_ITK_TCL=OFF -Ddouble-conversion_INCLUDE_DIRS=/usr/include/double-conversion -DExternalData_OBJECT_STORES=/var/tmp/portage/sci-libs/itk-5.0.1/work/InsightToolkit-5.0.1/.ExternalData -DModule_GenericLabelInterpolator:BOOL=ON -DModule_ITKReview:BOOL=ON -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DITK_USE_REVIEW=OFF -DITK_INSTALL_LIBRARY_DIR=lib64 -DITK_WRAP_PYTHON=ON -DITK_WRAP_DIMS=2;3 -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-libs/itk-5.0.1/work/itk-5.0.1_build/gentoo_toolchain.cmake  /var/tmp/portage/sci-libs/itk-5.0.1/work/InsightToolkit-5.0.1
```

I get the following error in my [build.log](https://github.com/InsightSoftwareConsortium/ITK/files/3575813/build.log). Any idea what's wrong?

**Comment by dzenanz** [comment] 2019-09-04 18:24
LabelImageGenericInterpolate  remote module is somewhat outdated, I think. That should be fixed in order to get a clean build.

**Comment by TheChymera** [comment] 2019-09-04 18:57
so in `5.0.1` Python support is broken if `LabelImageGenericInterpolate` is also installed?

**Comment by dzenanz** [comment] 2019-09-04 19:46
Possibly. I am build with Python and LabelInterpolate remote module to test. I suspect that the fix will be easy.

**Comment by dzenanz** [comment] 2019-09-05 17:57
The problem is with definition of [python wrapping](https://github.com/InsightSoftwareConsortium/ITKGenericLabelInterpolator/blob/master/wrapping/itkLabelImageGenericInterpolateImageFunction.wrap).

It generates this C++ code:
```C++
#ifdef ITK_WRAPPING_PARSER
namespace _wrapping_
{
  const char* const group = "itkLabelImageGenericInterpolateImageFunction";
  namespace wrappers
  {
    
    typedef itk::LabelImageGenericInterpolateImageFunction< itk::Image< signed short,2 >,double,float > itkLabelImageGenericInterpolateImageFunctionISS2DF;
    typedef itk::LabelImageGenericInterpolateImageFunction< itk::Image< signed short,2 >,double,float >::Pointer itkLabelImageGenericInterpolateImageFunctionISS2DF_Pointer;

    typedef itk::LabelImageGenericInterpolateImageFunction< itk::Image< signed short,2 >,double,double > itkLabelImageGenericInterpolateImageFunctionISS2DD;
    typedef itk::LabelImageGenericInterpolateImageFunction< itk::Image< signed short,2 >,double,double >::Pointer itkLabelImageGenericInterpolateImageFunctionISS2DD_Pointer;
...
```
the second template parameter is `double`, and it should be some interpolator, maybe linear or nearest neighbor. And this is a known [issue](https://github.com/InsightSoftwareConsortium/ITKGenericLabelInterpolator/issues/10). Somebody needs to update the wrapping. @thewtex usually does fixes like this, but he is out of office for the next few weeks.

**Closed by dzenanz** 2019-09-05 17:57 UTC
Labels: type:Infrastructure
