### ISSUE TITLE
Trying to compile VTK 4.13.3 with only ITKGroup_Core is generating few errors with xutility

### ISSUE THREAD

**Issue by al-sabr** [InsightSoftwareConsortium/ITK#2502] opened 2021-04-21 17:14 UTC
### Description

Compilation doesn't work for **gdcmMSFF**

### Steps to Reproduce

OPTIONS

ITK_BUILD_DEFAULT_MODULES:OFF
ITKGroup_Core:ON

1. Download from repo revision tag 4.13.3
2. Open CMake-GUI on Windows
3. Set ITK_BUILD_DEFAULT_MODULES:OFF and ITKGroup_Core:ON

### Expected behavior

Normal compilation

### Actual behavior

![image](https://user-images.githubusercontent.com/26530975/115593648-0de86580-a2d5-11eb-9edb-79ea50c9adf0.png)

### Reproducibility

100%

### Versions

v4.13.3

### Environment

Windows 10, Visual Studio 2019 Community, vcpkg, CMake 3.18.2

**Comment by dzenanz** [comment] 2021-04-21 18:02
I cannot reproduce this. But I do not have `vcpkg`. So that might be the source of your problem.

**Comment by al-sabr** [comment] 2021-04-22 10:50
How come that vcpkg is the problem? Based on what analysis?

**Comment by dzenanz** [comment] 2021-04-22 12:15
I use Windows 10, CMake 3.20.1, and up to date VS2019. And I cannot reproduce your problem. Hence, vcpkg is the most likely culprit.

**Comment by al-sabr** [comment] 2021-04-22 12:57
Ok you mean that I have packages installed within vcpkg which are also included inside of VTK that are conflicting?

**Comment by dzenanz** [comment] 2021-04-22 13:05
Do you have the latest VS? I have Version 16.9.4.

**Comment by thewtex** [comment] 2021-04-22 15:15
ITK 4.13 is no longer supported. These issues have been resolved in the latest version of ITK 5. Please migrate to ITK 5.

**Closed by thewtex** 2021-04-22 15:15 UTC
Labels: type:Bug

**Comment by al-sabr** [comment] 2021-04-23 07:15
I cannot migrate to ITK 5 because a lot of files are not present anymore and will require a huge refactoring of main project.

**Comment by dzenanz** [comment] 2021-04-23 12:58
[ITK 4.13](https://github.com/InsightSoftwareConsortium/ITK/releases/tag/v4.13.0) is now over 3 years old. While we will still accept other people's patches to it, we have stopped working on it.
