### ISSUE TITLE
ITK - c++ -  itkNeighborhoodOperatorImageFilter.hxx - Requested region is outside the largest possible region

### ISSUE THREAD

**Issue by ShibaPrasad** [InsightSoftwareConsortium/ITK#1016] opened 2019-06-13 16:03 UTC
### Description

**_Note:_**
I am trying to find the SIFT features and using ITK C++.
**Main program code:**
.
.
.
.
#ifdef DEBUG
  siftFilter1.writeImage(fixedImage, "tmp0.png");
  std::cout << std::endl << "Starting SIFT Feature Extraction...\n";  
#endif

  keypoints1 = siftFilter1.getSiftFeatures(fixedImage);
'
'
'
---------------------------------------------------------------
Input - Just 2 files: (file1 and file2)
-------------------------------------------
I am getting the below error:

itk::InvalidRequestedRegionError (0x55850d4e1260)
Location: "void itk::NeighborhoodOperatorImageFilter<TInputImage, TOutputImage, TOperatorValueType>::GenerateInputRequestedRegion() [with TInputImage = itk::Image<float, 3>; TOutputImage = itk::Image<float, 3>; TOperatorValueType = double]" 
File: /user/iibi/skuanar/itk-build/itkinstall/include/ITK-5.1/itkNeighborhoodOperatorImageFilter.hxx
Line: 72
Description: Requested region is (at least partially) outside the largest possible region.

**Comment by dzenanz** [comment] 2019-06-13 16:51
This bug report need more information.

**Comment by ShibaPrasad** [comment] 2019-06-13 17:01
Updated few information (if that helps)

**Comment by dzenanz** [comment] 2019-06-13 17:10
This is most likely a problem in SIFT filter. And where do you get the SIFT image filter? It doesn't appear to be part of the main repository.

Also, ideal way to reproduce a bug is with a [small example](http://sscce.org/) and input files it is operating on.

**Comment by ShibaPrasad** [comment] 2019-06-13 19:10
int main( int argc, char *argv[] )
{
  const unsigned int    Dimension = DIMENSION;

  // Default scale is 1.0
  double test_scale = 1.0;
  float test_rotate = 0.0;          // 0 degrees
  double test_crop = 0.5;
  //float test_rotate = 0.0874;     // 5 degrees
  //float test_rotate = 0.1748;     // 10 degrees
  int series_start = 1;
  int series_end = 9;
  int series_inc = 1;

  int mode = 'i';                   /* defaults to comparing 2 images */;
  int rotate_middle=0;              /* defaults to rotating around the origin */

#define OPT_SCALE 'x'
#define OPT_ROTATE 'r'
#define OPT_DIM 'd'
#define OPT_CROP 'c'
#define OPT_SERIES_START 's'
#define OPT_SERIES_END 'e'
#define OPT_SERIES_INC 'i'

  /* new Getopt code */
  while(1) {
    static struct option long_options[] =
      {
	/* These options set a flag.   */
	{"synthetic", 0, &mode, 's'},
	{"image", 0, &mode, 'i'},
	{"rotate-mid", 0, &rotate_middle, 1},
	/* These options don't set a flag.
	   We distinguish them by their indices.  */
	{"scale", required_argument, 0, OPT_SCALE},
	{"rotate", required_argument, 0, OPT_ROTATE},
	{"crop", required_argument, 0, OPT_CROP},
	{"series-start", required_argument, 0, OPT_SERIES_START},
	{"series-end", required_argument, 0, OPT_SERIES_END},
	{"series-inc", required_argument, 0, OPT_SERIES_INC},
	//	{"dimension", required_argument, 0, OPT_DIM},
	{0, 0, 0, 0}
      };    

    int optindex;
    int val = getopt_long(argc, argv, "", long_options, &optindex);

    if (val == -1)
      break;

    switch(val) {
    case OPT_SCALE:
      test_scale = atof(optarg);
      break;
    case OPT_ROTATE:
      if (atof(optarg) >= 0.0 && atof(optarg) <= 360.0)
      test_rotate = atof(optarg) * PI * 2.0 / 360.0;
      break;
    case OPT_CROP:
      if (atof(optarg) <= 1.0) {
	test_crop = atof(optarg);
      }
      break;
    case OPT_SERIES_START:
      series_start = atoi(optarg);
      break;
    case OPT_SERIES_END:
      series_end = atoi(optarg);
      break;
    case OPT_SERIES_INC:
      series_inc = atoi(optarg);
      break;
      /*
    case OPT_DIM:
      Dimension = atoi(optarg);
      break;
      */
    }
  }

  ARG_IMG1 = optind;
  ARG_IMG2 = optind+1;

  typedef  float  PixelType;
  typedef itk::Image< PixelType, Dimension >  FixedImageType;
  typedef itk::ScaleInvariantFeatureImageFilter<FixedImageType, Dimension> SiftFilterType;

  typedef itk::ImageSource< FixedImageType > ImageSourceType;

  ImageSourceType::Pointer fixedImageReader, fixedImageReader2;
 
  if( argc <= ARG_IMG1 || (mode == 'i' && argc <= ARG_IMG2))
    {
      std::cerr << "Incorrect number of parameters " << std::endl;
      std::cerr << std::endl;
      std::cerr << "siftkeys program ( ";
      std::cerr << DIMENSION << "D ";      
#ifdef SIFT_FEATURE
      std::cerr << "sift-feature ";
#else
      std::cerr << "histogram-feature ";
#endif
#ifdef REORIENT
      std::cerr << "reoriented ";
#endif
      std::cerr << ")" << std::endl;

      std::cerr << "Usage: \n";
      std::cerr  << argv[0] << " [options] ImageFile [ImageFile2]\n"; 
      std::cerr << "This program takes an input image file(s) and generates scale invariant features." << std::endl;
      std::cerr << std::endl;
      std::cerr << "Image Processing Options (Choose ONE):" << std::endl;
      std::cerr << "--image" << std::endl;
      std::cerr << " compare ImageFile and ImageFile2" << std::endl;
      std::cerr << "\nOR\n" << std::endl;
      std::cerr << "--synthetic" << std::endl;
      std::cerr << " compare ImageFile to synthetically generated version" << std::endl;
      std::cerr << "Synthetic Image Options:" << std::endl;
      std::cerr << "--rotate value" << std::endl;
      std::cerr << "  rotate synthetic image on first axis by value degrees" << std::endl;
      std::cerr << "--rotate-middle" << std::endl;
      std::cerr << "  centre of rotation at the centre of image (defaults to origin)" << std::endl;
      std::cerr << "--scale value" << std::endl;
      std::cerr << "  scale all axes of synthetic image by value" << std::endl;
      std::cerr << std::endl;
      return 1;
    }

  std::cerr << "Dimension = " << Dimension << "\n";
  std::cerr << "Test Scale = " << test_scale << "\n";
  std::cerr << "Test Rotate = " << test_rotate << "\n";
  std::cerr << "Image Crop Ratio (first 3D) = " << test_crop << "\n";
  std::cerr << "Mode = " << (char) mode << "\n";
  std::cerr << "ImageFile1 = " << argv[optind] << "\n";

  if (Dimension == 4) {
    std::cerr << "Image Series Start = " << series_start << "\n";
    std::cerr << "Image Series End = " << series_end << "\n";
    std::cerr << "Image Series Inc = " << series_inc << "\n";
  }

#ifdef SIFT_FEATURE
  std::cerr << "SIFT Feature\n" << std::endl;
#else
  std::cerr << "Histogram Feature\n" << std::endl;
#endif

#ifdef REORIENT
  std::cerr << "Reorientation enabled\n" << std::endl;  
#endif

  if (Dimension == 4) {
    /* Assume fileseries reader */
    typedef itk::ImageSeriesReader< FixedImageType  > FixedImageReaderType;
    FixedImageReaderType::Pointer tmpImageReader  = FixedImageReaderType::New();

    typedef itk::NumericSeriesFileNames NameGeneratorType;
    NameGeneratorType::Pointer nameGenerator = NameGeneratorType::New();
    
    nameGenerator->SetSeriesFormat( argv[ARG_IMG1] );
    nameGenerator->SetStartIndex( series_start );
    nameGenerator->SetEndIndex( series_end );
    nameGenerator->SetIncrementIndex( series_inc );
        
    tmpImageReader->SetFileNames( nameGenerator->GetFileNames() );

    fixedImageReader = tmpImageReader;
  } else {
    typedef itk::ImageFileReader< FixedImageType  > FixedImageReaderType;
    FixedImageReaderType::Pointer tmpImageReader  = FixedImageReaderType::New();
    tmpImageReader  = FixedImageReaderType::New();

    tmpImageReader->SetFileName(  argv[ARG_IMG1] );
    fixedImageReader=tmpImageReader;
  }
  fixedImageReader->Update();

  typedef itk::ScalableAffineTransform< double, Dimension > ScaleType;
#ifdef CROP
  ScaleType::Pointer no_transform = ScaleType::New();
  no_transform->SetIdentity();
  
  SiftFilterType::ResampleFilterType::Pointer cropper = SiftFilterType::ResampleFilterType::New();
  cropper->SetInput(fixedImageReader->GetOutput());
  FixedImageType::SizeType cropsize = 
    fixedImageReader->GetOutput()->GetLargestPossibleRegion().GetSize();
  for (int k = 0; k < Dimension; ++k) {
    if (k < 4)
      cropsize[k] = (int) (cropsize[k] * test_crop);
  }
  cropper->SetSize( cropsize );
  cropper->SetOutputSpacing(fixedImageReader->GetOutput()->GetSpacing());
  cropper->SetTransform(no_transform);
  cropper->Update();
  FixedImageType::Pointer fixedImage = cropper->GetOutput();
#else
  FixedImageType::Pointer fixedImage = fixedImageReader->GetOutput();  
#endif

  SiftFilterType::PointSetTypePointer keypoints1, keypoints2;

  SiftFilterType siftFilter1, siftFilter2;
  

#ifdef DEBUG
  siftFilter1.writeImage(fixedImage, "tmp0.png");
  std::cout << std::endl << "Starting SIFT Feature Extraction...\n";  
#endif

  keypoints1 = siftFilter1.getSiftFeatures(fixedImage);

  typedef itk::ScalableAffineTransform< double, Dimension > TestTransformType;
  TestTransformType::Pointer inv_test_transform;
  
  // Synthetic test image
  if (mode=='s') {
    std::cerr << std::endl << "Synthetic image mode\n";  
    TestTransformType::Pointer test_transform = TestTransformType::New();
    
    inv_test_transform = TestTransformType::New();
           
    TestTransformType::InputPointType translate_vector;
            
    test_transform->SetIdentity();
    test_transform->Scale( 1.0 / test_scale);
    if (rotate_middle) {
      std::cerr << "Rotation centred at middle of image." << std::endl;    
      /* Cycle through each dimension and shift by half*/
      FixedImageType::SizeType size = 
	fixedImage->GetLargestPossibleRegion().GetSize();
      for (int k = 0; k < Dimension; ++k)
	translate_vector[k] = size[k]/2.0;
      test_transform->SetCenter( translate_vector);
    } else {
      std::cerr << "Rotation centred at origin." << std::endl;    
    }
#if 0
    if (rotate_middle) {
      std::cerr << "Rotation centred at middle of image." << std::endl;    
      /* Cycle through each dimension and shift by half*/
      FixedImageType::SizeType size = 
	fixedImage->GetLargestPossibleRegion().GetSize();
      for (int k = 0; k < Dimension; ++k)
	translate_vector[k] = size[k]/2.0;
      test_transform->Translate( translate_vector);
    } else {
      std::cerr << "Rotation centred at origin." << std::endl;    
    }
#endif 

    test_transform->Rotate(0,1,test_rotate);

#if 0
    if (rotate_middle) {
      /* Cycle through each dimension and shift back*/
      for (int k = 0; k < Dimension; ++k)
	translate_vector[k] = -translate_vector[k];
      test_transform->Translate( translate_vector);
    }
#endif
    
    test_transform->GetInverse(inv_test_transform);
    
    {
      FixedImageType::Pointer scaledImage;
      
      SiftFilterType::ResampleFilterType::Pointer scaler = SiftFilterType::ResampleFilterType::New();
      scaler->SetInput(fixedImage);
      FixedImageType::SizeType size = 
	fixedImage->GetLargestPossibleRegion().GetSize();
      for (int k = 0; k < Dimension; ++k)
	size[k] = (unsigned int) floor(size[k] * test_scale);
      scaler->SetSize( size );
      scaler->SetOutputSpacing(fixedImage->GetSpacing());
      scaler->SetTransform(test_transform);
      scaler->Update();
      scaledImage = scaler->GetOutput();
      
#ifdef DEBUG
      siftFilter2.writeImage(scaledImage, "tmp1.png");
      std::cout << std::endl;
#endif
      keypoints2 = siftFilter2.getSiftFeatures(scaledImage);  
    }
    
    std::cerr << "Test Image Scale: " << test_scale << std::endl;
    // std::cerr << "Test Translate: " << test_translate << std::endl;
    std::cerr << "Test Image Rotate: " << test_rotate << std::endl;    
  } else if (mode == 'i') {
    std::cerr << std::endl << "Image Comparison mode\n";  
    inv_test_transform = NULL;

    if (Dimension == 4) {
      typedef itk::ImageSeriesReader< FixedImageType  > FixedImageReaderType;
      FixedImageReaderType::Pointer tmpImageReader  = FixedImageReaderType::New();
      tmpImageReader  = FixedImageReaderType::New();

      typedef itk::NumericSeriesFileNames NameGeneratorType;
      NameGeneratorType::Pointer nameGenerator = NameGeneratorType::New();
      
      nameGenerator->SetSeriesFormat( argv[ARG_IMG2] );
      nameGenerator->SetStartIndex( series_start );
      nameGenerator->SetEndIndex( series_end );
      nameGenerator->SetIncrementIndex( series_inc );
      
      tmpImageReader->SetFileNames( nameGenerator->GetFileNames() );
      fixedImageReader2 = tmpImageReader;
    } else {      
      typedef itk::ImageFileReader< FixedImageType  > FixedImageReaderType;
      FixedImageReaderType::Pointer tmpImageReader  = FixedImageReaderType::New();
      tmpImageReader  = FixedImageReaderType::New();

      tmpImageReader->SetFileName(  argv[ARG_IMG2] );
      fixedImageReader2 = tmpImageReader;
    }
    fixedImageReader2->Update();

#ifdef CROP
    SiftFilterType::ResampleFilterType::Pointer cropper2 = SiftFilterType::ResampleFilterType::New();
    cropper2->SetInput(fixedImageReader2->GetOutput());
    FixedImageType::SizeType cropsize2 = 
      fixedImageReader2->GetOutput()->GetLargestPossibleRegion().GetSize();
    for (int k = 0; k < Dimension; ++k) {
      if (k < 4)
	cropsize2[k] /= 2;
    }
    cropper2->SetSize( cropsize2 );
    cropper2->SetOutputSpacing(fixedImageReader2->GetOutput()->GetSpacing());
    cropper2->SetTransform(no_transform);
    cropper2->Update();
    FixedImageType::Pointer fixedImage2 = cropper2->GetOutput();
#else
    FixedImageType::Pointer fixedImage2 = fixedImageReader2->GetOutput();  
#endif

    keypoints2 = siftFilter2.getSiftFeatures(fixedImage2);
  }
  
  std::cerr << std::endl << "Matching Keypoints\n";  
  siftFilter2.MatchKeypointsPos(keypoints1, keypoints2, inv_test_transform);
#ifdef GENERATE_KEYS
  siftFilter2.MatchKeypointsFeatures(keypoints1, keypoints2, inv_test_transform);
#endif
  return 0;

}

**Comment by ShibaPrasad** [comment] 2019-06-13 19:13
I was trying to run the above program with 2 image input and throwing exceptions (after calling) - siftFilter1.writeImage()

**Comment by dzenanz** [comment] 2019-06-13 19:23
The code from [this paper](https://www.insight-journal.org/browse/publication/207) is now more than 10 years old. Where did you get `itkScaleInvariantFeatureImageFilter.h` and `.hxx` files from? Which version of ITK are you using? And your example is missing the includes - I cannot compile this.

**Comment by ShibaPrasad** [comment] 2019-06-13 19:35
I am using ITK-5 for this execution. Program able to compile properly. But throwing exception while I am running the program with 2 input images. Yes it's very old code.

**Comment by dzenanz** [comment] 2019-06-13 19:45
Well, this is not a bug then, but a feature request: update [IJ207](https://www.insight-journal.org/browse/publication/207) to work with ITK5.

I am closing this bug report. You can create a feature request for this. However, you will most likely have to implement it yourself.

**Closed by dzenanz** 2019-06-13 19:45 UTC
Labels: type:Bug

**Comment by thewtex** [comment] 2019-06-20 03:49
CC: @romangrothausmann

**Comment by romangrothausmann** [comment] 2019-06-20 14:10
Thanks for pinging me. Getting an implementation of SIFT into ITK was an idea for the WBIR hackathon last year, but it turned out to be a bigger effort than what I could realize in time. @thewtex pointed to an implementation in the [orfeo-toolbox](https://www.orfeo-toolbox.org//doxygen/classotb_1_1ImageToSIFTKeyPointSetFilter.html) which could serve as a basis but I did not find the time yet to follow this idea. 
The idea for getting it into ITK is that it could then be made available in SITK which is the base for SimpleElastix (SE), where SIFT could then be used in combination with landmark registration, as e.g. in the "regeister vertual stack slices" plug-in of Fiji. In contrast to that plug-in, SE offer many more registration techniques to refine an initial landmark registration and to use the whole image processing filters of SITK for intermediate stages.

**Comment by blowekamp** [comment] 2019-06-20 17:38
@romangrothausmann Broadly the SIFT method has two steps: 1 detect critical scale features in the image, and 2 extracting and encoding feature vector. It looks like the Orfeo-toolbox just does the first. Similarly, I have an implementation of a [LaplacianBlobDetector](https://github.com/blowekamp/itkScaleSpace/blob/master/include/itkMultiScaleLaplacianBlobDetectorImageFilter.h) based on ITK recursive Laplacian filter. ANTs has already found [this filter](https://github.com/ANTsX/ANTs/blob/c56a0d8ccf683731d0b93f7a9358d03939d1238b/Utilities/itkMultiScaleLaplacianBlobDetectorImageFilter.h) useful.  As I am sure you know the LoG and the DoG are very similar so the detected scale space extreme should be very similar as well. With a little TLC this filter could be moved to the SimpleFilters module ( I assume there is not enough interest for it to be in ITK proper. )

**Comment by romangrothausmann** [comment] 2019-06-21 08:41
Many thanks @blowekamp for the pointer. I'll have have look with the next registration project. 
PS: What does "TLC" mean?

**Comment by ShibaPrasad** [comment] 2019-07-11 16:28
Thank you all for the valuable comments.
