### ISSUE TITLE
Do not wrap signed distance map filters for integer image outputs

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITK#1975] opened 2020-08-31 21:41 UTC
The filters, Danielsson and Maurer, do not generate correct results with integer image outputs. We likely also want to add a concept check to avoid general C++ instantiation.

**Comment by thewtex** [comment] 2020-08-31 21:42
@Leengit could you please take a look at this?

**Comment by Leengit** [comment] 2020-09-04 17:37
Whether for Python wrapping or C++, is it that we want the input pixel type to be any of
- `WRAP_ITK_SCALAR`: `F`, `D`, `SC`, `SS`, `SL`, `SLL`, `UC`, `US`, `UL`, `ULL`
and the output pixel type to be any of
- `WRAP_ITK_REAL`: `F`, `D`
?

**Comment by dzenanz** [comment] 2020-09-04 19:22
At the very least `itkSignedMaurerDistanceMapImageFilter` sometimes produces incorrect results which are non-trivial to track down if integer output type is used. But possibly all of them.

And yes, we want to enable many input types and allow only `float` and `double` as output. In C++ preferably as a compile time warning, but since there is no such thing then as a concept check error.

**Comment by Leengit** [comment] 2020-09-08 13:25
Pull Request is https://github.com/InsightSoftwareConsortium/ITK/pull/1997.

**Comment by jhlegarreta** [comment] 2020-09-10 00:20
IIUC, this was successfully addressed in PR #1997, so the issue is no longer an issue :tada:  and it can be closed, right?

@Leengit in case you were not familiar with it, issues can automatically be closed when a linked PR gets merged if one of the supported keywords is used in the commit message/PR description. The documentation about that feature is [here](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). You may find useful tips there !

**Closed** 2020-09-10 14:51 UTC
Labels: area:Filtering, area:Python wrapping, type:Bug
