### ISSUE TITLE
[Question] Compile ITK with gcc 9

### ISSUE THREAD

**Issue by tarnh** [InsightSoftwareConsortium/ITK#1371] opened 2019-10-29 01:22 UTC
Dear ITK developers,

I currently need a OTB 6.2 superbuild. My distro ArchLinux has already switched over to gcc 9. Downgrading first seemed easy to me, but all packages in the main repos are now compiled to a newer version of libstdc++.

So I've tried to build https://github.com/InsightSoftwareConsortium/ITK/tree/release-4.13 with gcc-9, which currently fails [due to "deprecated copy" warnings](https://pastebin.com/vBpVaRiM). 

I assume that you are working on that.

How I can I patch the superbuild to compile with `-Wno-deprecated-copy` to fix my compilation problem now?

**Comment by thewtex** [comment] 2019-10-29 11:36
This seems to be a duplicate of https://github.com/InsightSoftwareConsortium/ITK/issues/1302

@tarnh it would be worth the effort upgrading to ITK 5 in the meantime.

CC: @phcerdan

**Comment by tarnh** [comment] 2019-10-29 12:25
Of course I'm using ITK 5 on my main system.
https://github.com/CNES/WASP is the culprit which pushes me to use the obsolete OTB 6.2.

**Comment by phcerdan** [comment] 2019-10-29 13:12
@tarnh Are you compiling with `-Werror`? I am able to compile ITK with gcc9, despite those warnings.

**Comment by tarnh** [comment] 2019-10-29 13:40
I'm building with an opaque "SuperBuild" script, so probably yes.

BTW: Do you have any experience in compiling HDF4? If not, this issue may be closed.

**Closed** 2019-11-27 14:25 UTC
Labels: type:Bug, type:Compiler
